# -*- coding: utf-8 -*-
"""collage_Database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQlB-0W-UTqPwQn9Wvo8BTu6UwaYcL5W
"""
import streamlit as st

import sqlite3
import pandas as pd

# إنشاء قاعدة بيانات داخل الذاكرة
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# جدول الطلاب
cursor.execute("""
CREATE TABLE Students (
    StudentID INTEGER PRIMARY KEY AUTOINCREMENT,
    FullName TEXT NOT NULL,
    Department TEXT,
    Email TEXT,
    EnrollmentYear INTEGER
);
""")

# جدول المقررات
cursor.execute("""
CREATE TABLE Courses (
    CourseID INTEGER PRIMARY KEY AUTOINCREMENT,
    CourseName TEXT NOT NULL,
    Credits INTEGER,
    Department TEXT
);
""")

# جدول الأساتذة
cursor.execute("""
CREATE TABLE Professors (
    ProfessorID INTEGER PRIMARY KEY AUTOINCREMENT,
    FullName TEXT NOT NULL,
    Department TEXT,
    Email TEXT
);
""")

# جدول تسجيل المقررات
cursor.execute("""
CREATE TABLE Enrollments (
    EnrollmentID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER,
    CourseID INTEGER,
    Grade TEXT,
    FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID)
);
""")

# إدخال طلاب
cursor.executemany("""
INSERT INTO Students (FullName, Department, Email, EnrollmentYear)
VALUES (?, ?, ?, ?)
""", [
    ("Ahmed Ali", "Computer Science", "ahmed.cs@example.com", 2022),
    ("Mona Hassan", "Business", "mona.bus@example.com", 2021),
    ("Omar Youssef", "Engineering", "omar.eng@example.com", 2023)
])

# إدخال مقررات
cursor.executemany("""
INSERT INTO Courses (CourseName, Credits, Department)
VALUES (?, ?, ?)
""", [
    ("Database Systems", 3, "Computer Science"),
    ("Marketing 101", 2, "Business"),
    ("Thermodynamics", 4, "Engineering")
])

# إدخال أساتذة
cursor.executemany("""
INSERT INTO Professors (FullName, Department, Email)
VALUES (?, ?, ?)
""", [
    ("Dr. Samir Fahmy", "Computer Science", "samir.cs@example.com"),
    ("Dr. Hala Ibrahim", "Business", "hala.bus@example.com"),
    ("Dr. Mahmoud Tarek", "Engineering", "mahmoud.eng@example.com")
])

# إدخال تسجيلات طلاب
cursor.executemany("""
INSERT INTO Enrollments (StudentID, CourseID, Grade)
VALUES (?, ?, ?)
""", [
    (1, 1, "A"),
    (2, 2, "B+"),
    (3, 3, "A-"),
    (1, 2, "B")  # أحمد سجل مادة من إدارة الأعمال
])

conn.commit()

# عرض كل الطلاب
df_students = pd.read_sql("SELECT * FROM Students", conn)
st.write("📌 الطلاب:")
st.dataframe(df_students)

# عرض كل المقررات
df_courses = pd.read_sql("SELECT * FROM Courses", conn)
st.write("📌 المقررات:")
st.dataframe(df_courses)

# عرض كل الأساتذة
df_professors = pd.read_sql("SELECT * FROM Professors", conn)
st.write("📌 الأساتذة:")
st.dataframe(df_professors)

# عرض تسجيلات الطلاب مع تفاصيل المقررات
query = """
SELECT
    E.EnrollmentID, S.FullName AS StudentName, C.CourseName, E.Grade
FROM
    Enrollments E
JOIN Students S ON E.StudentID = S.StudentID
JOIN Courses C ON E.CourseID = C.CourseID;
"""
df_enrollments = pd.read_sql(query, conn)
print("📌 تسجيلات الطلاب:")
display(df_enrollments)

